version: "3.8"
services:
  connector-proxy-status-im: &connector-proxy-status-im
    container_name: connector-proxy-status-im
    profiles:
      - run
    build:
      context: .
    environment:
      - FLASK_ENV=${FLASK_ENV:-development}
      - FLASK_DEBUG=0
      - FLASK_SESSION_SECRET_KEY=${FLASK_SESSION_SECRET_KEY:-super_secret_key}
    ports:
      - "7004:7004"
    network_mode: host
    healthcheck:
      test: curl localhost:7004/liveness --fail
      interval: 10s
      timeout: 5s
      retries: 20
