[tool.poetry]
name = "cmd-proxy"
version = "0.1.0"
description = ""
authors = ["Jon Herron <jon.herron@yahoo.com>"]

[tool.poetry.dependencies]
python = "^3.10"
Flask = "*"

cmd-proxy_xero = {develop = true, path = "/home/jon/dev/cmd-proxy_xero"}

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
